# Generated by Django 4.1.2 on 2022-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_expenses_person_remove_khabgah_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
