# Generated by Django 4.1.2 on 2022-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_person_adminswitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adminswitch',
            field=models.BooleanField(default=False),
        ),
    ]
