# Generated by Django 4.1.2 on 2022-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_person_adminswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='week',
            field=models.CharField(choices=[('vah', 'VAH'), ('rez', 'REZ')], default='user', max_length=25),
        ),
    ]
