# Generated by Django 4.1.2 on 2022-11-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_person_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='week',
        ),
    ]
