# Generated by Django 4.1.2 on 2022-11-15 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_person_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
