# Generated by Django 4.1.2 on 2022-11-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_person_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.TextField(default='null'),
        ),
    ]
